# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-18 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lamination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lam_size', models.CharField(max_length=20)),
                ('measure_A', models.FloatField()),
                ('measure_B', models.FloatField()),
                ('measure_C', models.FloatField()),
                ('measure_D', models.FloatField()),
                ('measure_E', models.FloatField()),
                ('measure_F', models.FloatField()),
                ('measure_G', models.FloatField()),
                ('path_length', models.FloatField()),
                ('window_area', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Winding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turns', models.IntegerField()),
                ('layers', models.IntegerField()),
                ('turns_per_layer', models.IntegerField()),
                ('voltage', models.FloatField()),
                ('current', models.FloatField()),
                ('mean_length_turns', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Wire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.FloatField()),
                ('grade_1_dia_max', models.FloatField()),
                ('grade_2_dia_max', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='winding',
            name='wire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designer.Wire'),
        ),
    ]
