# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-02 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Inductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=100)),
                ('target_inductance', models.FloatField()),
                ('current_density', models.FloatField()),
                ('dc_current', models.FloatField()),
                ('ac_voltage', models.FloatField()),
                ('core', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designer.Core')),
            ],
        ),
        migrations.CreateModel(
            name='steel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('thickness', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='lamination',
            old_name='measure_A',
            new_name='tongue_width',
        ),
        migrations.RemoveField(
            model_name='lamination',
            name='measure_B',
        ),
        migrations.RemoveField(
            model_name='lamination',
            name='measure_C',
        ),
        migrations.RemoveField(
            model_name='lamination',
            name='measure_D',
        ),
        migrations.RemoveField(
            model_name='lamination',
            name='measure_E',
        ),
        migrations.RemoveField(
            model_name='lamination',
            name='measure_F',
        ),
        migrations.RemoveField(
            model_name='lamination',
            name='measure_G',
        ),
        migrations.RemoveField(
            model_name='lamination',
            name='path_length',
        ),
        migrations.RemoveField(
            model_name='lamination',
            name='window_area',
        ),
        migrations.RemoveField(
            model_name='winding',
            name='current',
        ),
        migrations.RemoveField(
            model_name='winding',
            name='mean_length_turns',
        ),
        migrations.RemoveField(
            model_name='winding',
            name='voltage',
        ),
        migrations.AddField(
            model_name='inductor',
            name='winding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designer.Winding'),
        ),
        migrations.AddField(
            model_name='core',
            name='laminations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designer.Lamination'),
        ),
        migrations.AddField(
            model_name='core',
            name='steel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designer.steel'),
        ),
    ]
