# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-05 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0002_auto_20180502_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lamination',
            old_name='lam_size',
            new_name='name',
        ),
    ]
