# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-07 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0003_auto_20180505_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='core',
            name='steel',
        ),
    ]
