# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-07 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0004_remove_core_steel'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
