# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-12 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0005_core_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='stack_factor',
            field=models.FloatField(default=0.97),
        ),
    ]
