# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-12 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0006_core_stack_factor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bobbin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('SS', 'SS'), ('DS', 'DS'), ('SDS', 'SDS')], max_length=100)),
                ('section_winding_length', models.FloatField()),
                ('section_winding_depth', models.FloatField()),
                ('meterial_thickness', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='core',
            name='stack_factor',
            field=models.FloatField(default=0.92),
        ),
        migrations.AddField(
            model_name='bobbin',
            name='core',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designer.Core'),
        ),
    ]
