# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-14 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0007_auto_20180512_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobbin',
            name='number_terminals',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='bobbin',
            name='terminals',
            field=models.BooleanField(default=True),
        ),
    ]
