# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-14 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0008_auto_20180514_0748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bobbin',
            old_name='terminals',
            new_name='has_terminals',
        ),
    ]
