# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-26 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0011_auto_20180521_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inductor',
            name='core',
        ),
        migrations.AddField(
            model_name='inductor',
            name='bobbin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='designer.Bobbin'),
            preserve_default=False,
        ),
    ]
