# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-31 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0013_auto_20180531_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='winding',
            name='winding_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
