# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-31 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0015_winding_taps'),
    ]

    operations = [
        migrations.AddField(
            model_name='inductor',
            name='total_gap',
            field=models.FloatField(default=0.4),
            preserve_default=False,
        ),
    ]
