# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-01 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0016_inductor_total_gap'),
    ]

    operations = [
        migrations.AddField(
            model_name='inductor',
            name='steel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='designer.Steel'),
            preserve_default=False,
        ),
    ]
