# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-01 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0017_inductor_steel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inductor',
            name='steel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designer.Steel'),
        ),
    ]
