# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-02 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('designer', '0018_auto_20180601_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='winding',
            name='wire_grade',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inductor',
            name='steel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designer.Steel'),
        ),
    ]
